// Archivo vacío: no se requiere NgModule con componentes standalone.
// Este archivo no es necesario si usas componentes standalone.
// ...puedes dejarlo vacío o eliminarlo...
// ...puedes dejarlo vacío o eliminarlo...
